data:
  data_source_type: "real_world_data"
  hypernetwork_name: "senate-commitees"

model:
  name: "clustering"
  curvature_form: "Forman"
  internal_measure: "modularity"
  modularity_type: "linear"
  external_measure: "NMI"