data:
  data_source_type: "synthetic_data"
  hypernetwork_name: "cluster_id6_low_noise"

model:
  name: "clustering"
  curvature_form: "OR_MMOT"
  internal_measure: "modularity"
  modularity_type: "linear"
  external_measure: "both"
  target_distribution: "None" # "None" and [0.25,0.15,0.1]
  max_iterations: 5000
  number_of_target_cluster: 4
  ot_computation: "NA"